version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo I could have put a command here
  pre_build:
    commands:
      - echo Here are some more commands
      - echo Here are some more commands
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies
      - pip install pipenv
      - echo Running tests
      - pipenv install --dev
      - sh bootstrap.sh
      - pipenv run pytest > myoutput.log

  post_build:
    commands:
      - echo Build completed on `date`
reports:
  myReport:
    files:
      - "**/myoutput.log"
cache:
  paths:
    - "/root/.cache/pip/*"