API_V1_STR = "/api"
PROJECT_NAME = "FastAPI-AWS-Lambda-Proxy-API"

SECTION_LIST = [
    {
        "section": "applicant",
        "inputs": [
            "medicaid_facility_type",
            "state_of_service",
            "relationship",
            "other_relationship_to_applicant",
            "user_legal_status",
            "application_info.application_type",
            "applicant_info.first_name",
            "applicant_info.last_name",
            "applicant_info.gender",
            "applicant_info.own_responsible_party",
            "will_user_add_contacts",
            "contacts",
            "spouse_info.first_name",
            "spouse_info.last_name",
            "spouse_info.spouse_own_responsible_party",
            "spouse_legal_status",
            "living_info.lives_in",
            "living_info.spouse_lives_in",
            "home_address.address1",
            "home_address.city",
            "home_address.state",
            "home_address.zip",
            "home_address.month_year_of_move_in",
            "home_address.type",
            "verification_info_documents.marriage_certificate",
            "request_questions.marriage_certificate_spouse_name",
            "request_questions.date_of_marriage",
            "request_questions.place_of_marriage",
            "spouse_info.spouse_living_info_spouse_location",
            "home_address.has_homeowners_association_fee",
            "facility.type",
            "facility.name",
            "facility.admission_date",
            "facility.family_supplementing_private_room",
            "facility.has_private_pay_requirement",
            "facility.how_long_private_pay",
            "facility.pay_type",
            "spouse_facility.name",
            "spouse_facility.type",
            "spouse_facility.spouse_admission_date",
            "spouse_facility.spouse_pay_type",
            "facility.aslf_pay_type",
            "spouse_facility.spouse_aslf_pay_type",
            "facility.medicare_cut_date",
            "spouse_facility.spouse_medicare_cut_date",
            "facility.medicaid_pending_as_of_date",
            "spouse_facility.spouse_medicaid_pending_as_of_date",
            "spouse_facility.spouse_family_supplementing_private_room",
            "spouse_facility.spouse_has_private_pay_requirement",
            "spouse_facility.spouse_how_long_private_pay",
            "previous_addresses"
        ]
    },
    {
        "section": "verify",
        "inputs": [
            "verification_documents_info.ss_card",
            "verification_documents_info.medicare_card",
            "verification_details_info.date_of_birth",
            "verification_details_info.ssn",
            "verification_details_info.marital_status",
            "verification_info_documents.divorce_decree",
            "request_questions.divorce_date",
            "request_questions.divorce_place",
            "request_questions.divorce_lawyer",
            "verification_info_documents.death_certificate",
            "request_questions.death_place",
            "request_questions.funeral_home_cemetery",
            "verification_details_info.marital_status_last_five_years",
            "verification_details_info.separation_date",
            "spouse_verification_documents_info.spouse_ss_card",
            "spouse_verification_documents_info.spouse_medicare_card",
            "verification_details_info.spouse_name",
            "verification_details_info.will_ex_cooperate",
            "verification_details_info.spouse_date_of_death",
            "verification_details_info.spouse_date_of_birth",
            "verification_details_info.spouse_ssn",
            "executor_of_estate.was_executor",
            "verification_info_documents.executor_paperwork",
            "executor_of_estate.willing_sign_documents",
            "executor_of_estate.name",
            "executor_of_estate.phone",
            "executor_of_estate.email",
            "verification_documents_info.",
            "spouse_verification_documents_info."
        ]
    },
    {
        "section": "insurance",
        "inputs": [
            "insurance_policies.insurance_policies_details"
        ]
    },
    {
        "section": "income",
        "inputs": [
            "employment_income.income_employment_details"
        ]
    },
    {
        "section": "general",
        "inputs": [
            "taxes.filed_taxes_within_lookback",
            "general_documents.tax_returns",
            "request_questions.accountant_name",
            "request_questions.accountant_phone",
            "general.are_there_vehicles",
            "general.vehicles",
            "general.applicant_currently_owns_properties",
            "general.properties",
            "were_properties_sold",
            "general.property_proceeds",
            "burial_plot.burial_plot",
            "account_set_aside_for_burial.prepaid_funeral_contract",
            "account_set_aside_for_burial.is_irrevocable",
            "final_details_documents.cemetery_paperwork",
            "request_questions.name_of_cemetery",
            "request_questions.cemetery_address",
            "request_questions.cemetery_phone",
            "final_details_documents.funeral_paperwork",
            "request_questions.funeral_home",
            "funeral_plan.plan",
            "account_set_aside_for_burial.have_account",
            "other.how_many_children",
            "other.has_disabled_child_or_grandchild",
            "other.disabled_child_name",
            "other.disabled_grandchild_name",
            "other.child_gets_ssd",
            "other.special_needs_trust",
            "general_documents.special_needs_trust_document",
            "ssd_award_letter",
            "other.has_trust",
            "general_documents.trust_document",
            "other.clinical_diagnosis",
            "other.inheritance_settlement",
            "other.inheritance_settlement_notes",
            "other.has_outstanding_payments",
            "other.outstanding_payments_notes",
            "other.served_in_military",
            "other.spouse_title_19",
            "request_questions."
        ]
    },
    {
        "section": "financial",
        "inputs": [
            "financials.account_details",
            "financials.address_on_file_with_financial_institutions-address",
            "financials.address_on_file_with_financial_institutions-city",
            "financials.address_on_file_with_financial_institutions-state",
            "financials.address_on_file_with_financial_institutions-zip",
            "financials.who_has_checkbooks",
            "financials.life_insurance_stocks_details"
        ]
    }
]