AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TurbocaidLambdaProxy:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.handler
      Runtime: python3.7
      CodeUri: .

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  TurbocaidLambdaProxy:
    Description: "turbocaid lambda proxy"
